In [99]:
df=pd.read_json('https://raw.githubusercontent.com/ComputationalMethods/Evaluacion_2021-2/main/calificaciones.json',dtype={'student_id':str})

In [100]:
df=df[df['student_id']!='0000000000'].reset_index(drop=True)

download from MARES

In [101]:
tm=pd.read_csv('listado.csv',dtype={'Cédula':str})

In [102]:
for i in range(1,4):
    df[f'E{i}']=df[f'Parcial_{i}'].str['value']

In [103]:
df['TF']=df['Trabajo_Final'].str['value']

In [104]:
for i in range(3):
    df[f'T{i+1}']=df['Tareas'].str[i].str['value']

In [105]:
df['TA']=df['Tareas'].apply(lambda l: [d for d in l if d.get('Taller')]).str[0].str['value'].fillna(0.)

In [106]:
df['Cédula']=df['student_id']

In [107]:
dff=df[['Cédula','E1','E2','E3','TF','T1','T2','T3','TA']]

In [108]:
dff=tm[['Cédula']].merge(dff,on='Cédula',how='left').fillna(0)
dff.to_csv('calificaciones.csv',index=False)

In [109]:
dff

        Cédula   E1   E2   E3   TF   T1   T2   T3   TA
0   1193090281  4.5  5.0  5.0  4.5  5.0  5.0  5.0  4.0
1   1216722165  4.0  3.0  3.5  5.0  5.0  5.0  5.0  4.1
2   1000307065  5.0  5.0  5.0  4.5  5.0  5.0  5.0  4.5
3   1000439477  4.5  4.0  4.5  5.0  0.0  0.0  0.0  4.6
4   1017259461  4.5  3.5  4.5  4.5  5.0  0.0  0.0  2.2
5   1001469185  4.5  5.0  4.5  5.0  5.0  5.0  5.0  4.2
6   1000413445  5.0  5.0  5.0  5.0  5.0  5.0  5.0  3.8
7   1001735333  4.5  4.0  4.5  4.5  5.0  0.0  0.0  4.5
8   1003970969  3.0  4.5  5.0  5.0  5.0  5.0  0.0  1.1
9   1006508118  4.5  4.0  4.5  4.5  5.0  5.0  5.0  4.6
10  1001013769  0.0  0.0  0.0  0.0  5.0  5.0  0.0  0.3
11  1004579495  5.0  4.0  4.5  4.5  5.0  0.0  0.0  2.7
12  1036960267  5.0  5.0  4.5  4.5  5.0  5.0  5.0  4.7
13  1192914660  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [110]:
import pandas as pd
#REORDER=True
#dff=pd.read_csv('https://github.com/ComputationalMethods/Evaluacion_2021-2/raw/main/calificaciones.csv')
dff['T']=((  (dff.T1+dff.T2+dff.T3)/3*0.25+dff.TA*0.75   )).round(1)
dff['F']=(dff.E1+dff.E2+dff.E3+dff.TF+dff['T'])/5

dff[['Cédula','E1','E2','E3','TF','T','F']].fillna(0)

        Cédula   E1   E2   E3   TF    T     F
0   1193090281  4.5  5.0  5.0  4.5  4.2  4.64
1   1216722165  4.0  3.0  3.5  5.0  4.3  3.96
2   1000307065  5.0  5.0  5.0  4.5  4.6  4.82
3   1000439477  4.5  4.0  4.5  5.0  3.4  4.28
4   1017259461  4.5  3.5  4.5  4.5  2.1  3.82
5   1001469185  4.5  5.0  4.5  5.0  4.4  4.68
6   1000413445  5.0  5.0  5.0  5.0  4.1  4.82
7   1001735333  4.5  4.0  4.5  4.5  3.8  4.26
8   1003970969  3.0  4.5  5.0  5.0  1.7  3.84
9   1006508118  4.5  4.0  4.5  4.5  4.7  4.44
10  1001013769  0.0  0.0  0.0  0.0  1.1  0.22
11  1004579495  5.0  4.0  4.5  4.5  2.4  4.08
12  1036960267  5.0  5.0  4.5  4.5  4.8  4.76
13  1192914660  0.0  0.0  0.0  0.0  0.0  0.00

In [111]:
df.to_csv('calificaciones.csv',index=False)

In [78]:
5*0.25+5*0.75

5.0

In [84]:
pd.read_csv('calificaciones.csv')

        Cédula   E1   E2   E3   TF   T1   T2   T3   TA    T     F
0   1152457227  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.2  0.04
1   1001735333  4.5  4.0  4.5  4.5  5.0  0.0  0.0  4.5  1.9  3.88
2   1003970969  3.0  4.5  5.0  5.0  5.0  5.0  0.0  1.1  0.8  3.66
3   1000439477  4.5  4.0  4.5  5.0  0.0  0.0  0.0  4.6  1.7  3.94
4   1007362148  5.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.2  1.04
5   1017259461  4.5  3.5  4.5  4.5  5.0  0.0  0.0  2.2  1.0  3.60
6   1004579495  5.0  4.0  4.5  4.5  5.0  0.0  0.0  2.7  1.2  3.84
7   1006508118  4.5  4.0  4.5  4.5  5.0  5.0  5.0  4.6  2.3  3.96
8   1000307065  5.0  5.0  5.0  4.5  5.0  5.0  5.0  4.5  2.3  4.36
9   1216722165  4.0  3.0  3.5  5.0  5.0  5.0  5.0  4.1  2.2  3.54
10  1001013769  0.0  0.0  0.0  0.0  5.0  5.0  0.0  0.3  0.5  0.10
11  1001228880  3.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.2  0.64
12  1003315591  2.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.2  0.44
13  1000413445  5.0  5.0  5.0  5.0  5.0  5.0  5.0  3.8  2.0  4.40
14  1001469185  4.5  5.0  4.5  5.0  5.0  5.0  5.0  4.2  2.2  4.24
15  1000203739  2.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.2  0.44
16  1036960267  5.0  5.0  4.5  4.5  5.0  5.0  5.0  4.7  2.4  4.28
17  1193090281  4.5  5.0  5.0  4.5  5.0  5.0  5.0  4.0  2.1  4.22